<?php
/*
AUTHOR:- RITHUNAND [BENCHAMXD]
CHANNEL:- @INDUSBOTS 
THIS REPO IS LICENCED WITH GENERAL PUBLIC LICENSE VERSION:3.0
(c) RITHUNAND K
*/
$TG_BOT_TOKEN = $_ENV['1882193391:AAFqWksOsBa8gA46Bpg5SSahM5Y7fklLrYU'];
$BOT_NAME = $_ENV['Yukino'];
$BOT_USERNAME = $_ENV['@Yukiinobot'];

?>
